#!/usr/bin/env bash
# ─── Add an app to nginx reverse proxy ───────────────────
# Usage: bash add-app.sh <app-name> <port> [domain]
#   app-name: short name (e.g. "myapp")
#   port:     localhost port the app listens on (e.g. 3000)
#   domain:   optional custom domain (default: <app-name>.gn01stic.gr)

set -euo pipefail
APP="${1:-}"
PORT="${2:-}"
DOMAIN="${3:-}"

if [ -z "$APP" ] || [ -z "$PORT" ]; then
    echo "Usage: bash add-app.sh <app-name> <port> [domain]"
    echo "  Example: bash add-app.sh todo-api 3000 todo.gn01stic.gr"
    exit 1
fi

APP_DOMAIN="${DOMAIN:-$APP.gn01stic.gr}"
CONF="/etc/nginx/conf.d/apps/${APP}.conf"

echo ">>> Adding app: $APP on port $PORT ($APP_DOMAIN)"

sudo tee "$CONF" > /dev/null << EOF
# Auto-generated by CA — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# App: $APP  Port: $PORT  Domain: $APP_DOMAIN

location / {
    proxy_pass http://127.0.0.1:$PORT;
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
}
EOF

echo "  Created $CONF"

# Test and reload
sudo nginx -t && sudo systemctl reload nginx
echo "  nginx reloaded — $APP is now live at http://$APP_DOMAIN"
echo ""
echo "  To add SSL: bash /opt/apps/ssl-cert.sh $APP_DOMAIN"
